source /jizhicfs/pinxuezhao/lhy/HSPMD_start.sh

# 务必要取消代理
# 不然grpc会走代理出现连接不上的问题
unset http_proxy
unset https_proxy

export PATH="/jizhicfs/pinxuezhao/lhy/env/miniconda3/envs/hspmd-py/bin:${PATH}"

# export HSPMD_P2P=SINGLE_COMMUNICATOR
# export HSPMD_BRIDGE=SINGLE_COMMUNICATOR
# export HSPMD_OVERLAP_GRAD_REDUCE=ALL_STAGES
export HSPMD_SHAPE_MISMATCH=BRIDGE_SUBGRAPH
export HSPMD_SWITCH_ALGORITHM=NEW_GREEDY
export HSPMD_SWITCH_PROFILE=TIME
export HSPMD_SWITCH_BUFFER=TRUE
# export HSPMD_FAILURE_DEVICES="32,33,34,35,36,37,38,39"
export HSPMD_FAILURE_DEVICES="24,25,26,27,28,29,30,31"
export HSPMD_INTERNAL_LOG_LEVEL=INFO
export HSPMD_STRAGGLER=ANALYSIS

export HSPMD_MEMORY_PROFILE=WARN
export HSPMD_MAX_SPLIT_SIZE_MB=200
export HSPMD_MAX_INTERNAL_FRAGMENT_SIZE_MB=20
# export HSPMD_MAX_SPLIT_SIZE_MB=1000000
# export HSPMD_MAX_INTERNAL_FRAGMENT_SIZE_MB=0
# export HSPMD_PRE_ALLOCATE_SIZE_MB=74000

# Using multi-stream cuda event to watch time elaspe is inaccurate!
# export HSPMD_PARALLEL_ATTN=ANALYSIS
export HSPMD_PARALLEL_ATTN_SPLIT_PATTERN=NORMAL

# 设置网络接口相关的环境变量
export NCCL_SOCKET_IFNAME=bond1
export UCX_NET_DEVICES=bond1
export NCCL_IB_HCA="mlx5_bond_1,mlx5_bond_5,mlx5_bond_3,mlx5_bond_7,mlx5_bond_4,mlx5_bond_8,mlx5_bond_2,mlx5_bond_6"

# 设置NCCL相关的环境变量
export NCCL_IB_DISABLE=0
export NCCL_IB_GID_INDEX=3
export NCCL_IB_CUDA_SUPPORT=1
export NCCL_DEBUG=VERSION
export NCCL_NET_GDR_READ=1
export NCCL_SOCKET_NTHREADS=8
export NCCL_COLLNET_ENABLE=0
export NCCL_NVLS_ENABLE=0
export NCCL_NET_GDR_LEVEL=2
export NCCL_IB_QPS_PER_CONNECTION=4
export NCCL_IB_TC=160
export NCCL_PXN_DISABLE=0

# 设置NCCL相关的环境变量
export NCCL_IB_DISABLE=0
export NCCL_IB_GID_INDEX=3
export NCCL_IB_CUDA_SUPPORT=1
export NCCL_DEBUG=VERSION
export NCCL_NET_GDR_READ=1
export NCCL_SOCKET_NTHREADS=8
export NCCL_COLLNET_ENABLE=0
export NCCL_NVLS_ENABLE=0
export NCCL_NET_GDR_LEVEL=2
export NCCL_IB_QPS_PER_CONNECTION=4
export NCCL_IB_TC=160
export NCCL_PXN_DISABLE=0

# SHARP相关的环境变量
export SHARP_COLL_ENABLE_SAT=0

# CUDA相关的环境变量
export CUDA_DEVICE_MAX_CONNECTIONS=1

echo "env done"
